source "https://rubygems.org"
ruby RUBY_VERSION

gem 'jekyll', '~> 3.4'


gem 'github-pages-health-check', '~> 1.3', '>= 1.3.1'

group :jekyll_plugins do
  # https://pages.github.com/versions/
  # gem "github-pages"
  # We install only what we use
  gem 'jekyll-avatar', '~> 0.4.2'
  gem 'jekyll-default-layout', '~> 0.1.4'
  gem 'jekyll-gist', '~> 1.4'
  gem 'jekyll-feed', '~> 0.9.1'
  gem 'jekyll-paginate', '~> 1.1'
  gem 'jekyll-relative-links', '~> 0.3.0'
  gem 'jekyll-seo-tag', '~> 2.1'
  gem 'jekyll-sitemap', '~> 1.0'
  gem 'jemoji', '~> 0.8.0'

  # Disabled
  # gem 'jekyll-github-metadata', '~> 2.3', '>= 2.3.1'
  # gem 'jekyll-mentions', '~> 1.2'
  # gem 'jekyll-readme-index', '~> 0.1.0'
  # gem 'jekyll-redirect-from', '~> 0.12.1'
  # gem 'jekyll-html-pipeline', '~> 1.0'

  # Themes
  gem 'jekyll-swiss', '~> 0.4.0'
  gem 'minima', '~> 2.1'

  # Tools
  gem 'jekyll-livereload'
  gem 'jekyll-coffeescript', '~> 1.0', '>= 1.0.2'

end