require "rubygems"
require "tmpdir"

require "bundler/setup"
require "jekyll"
require "socket"

# Change your GitHub reponame
GITHUB_REPONAME = "mintusers-gr/mintusers-gr.github.io"


desc "Generate blog files"
task :generate do
  Jekyll::Site.new(
      Jekyll.configuration({source: ".", destination: "../_site"})
  ).process
end


desc "Generate and publish blog to gh-pages"
task :publish => [:generate] do
  hostname = Socket.gethostbyname(Socket.gethostname).first
  if "local.mintusers.me" != hostname
    system "git push origin master"
    Dir.mktmpdir do |tmp|
      cp_r "../_site/.", tmp

      pwd = Dir.pwd
      Dir.chdir tmp

      system "git init"
      system "git add ."
      message = "Site updated at #{Time.now.utc}"
      system "git commit -m #{message.inspect}"
      system "git remote add origin git@github.com:#{GITHUB_REPONAME}.git"
      system "git push origin master --force"

      Dir.chdir pwd
    end
  else
    print "ERROR: Issue the generate command from the host. Not from the virtual machine.\n"
    print "       The website is NOT updated.\n"
    print "       Sad :-{\n"
  end
end
