source "https://rubygems.org"
ruby RUBY_VERSION

gem 'jekyll', '~> 3.4'
gem 'classifier-reborn'

group :jekyll_plugins do
  gem 'jekyll-last-modified-at'
  gem 'jekyll-livereload'
  gem 'jekyll-feed'
  gem 'jekyll-gist'
  gem 'jekyll-relative-links'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jemoji'
  # Theme
  gem 'minima'

  # Graphviz support
  gem 'jekyll-graphviz'
end
